### ISSUE TITLE
consider exposing on_attach option

### ISSUE THREAD

**Issue by ehaynes99** [esmuellert/nvim-eslint#2]
First of all, great work here. I've been battling eslint for a while now, and started looking in to how to debug it when I found this. Since switching, I'm not having the problems I was trying to debug anymore, so didn't even need to. :smile: 

It would be really convenient if the options allowed an `on_attach` function to customize it, create buffer scoped key mappings, etc. E.g.
```lua
on_attach = function(client, bufnr)
  client.server_capabilities.documentFormattingProvider = true

  local format = function()
    vim.lsp.buf.format({ timeout_ms = 2000 })
  end
  vim.keymap.set('n', 'ff', format, { silent = true, buffer = bufnr, desc = 'eslint fix' })
end,
```

It could just be directly passed to `vim.lsp.start` and wouldn't require a default value.

**Comment by esmuellert** [comment]
Thanks for the suggestions and PR! Yes, it is definitely great to expose `on_attach` setting. I have merged your changes :)
